name: Component Tests

on:
  push:
    branches:
      - testCase_feature  # only run on pushes to feature branch
  workflow_dispatch:      # allows manual triggering if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm ci
        npm install @testing-library/react @testing-library/jest-dom --save-dev
        
    - name: Run Tests
      run: npm test
      env:
        CI: true
        NODE_ENV: test
