name: Component Tests

on:
  push:
    branches:
      - testCase_feature
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: |
        npm install --legacy-peer-deps
        npm install @testing-library/react@^11.2.5 @testing-library/jest-dom@^5.16.5 --save-dev --legacy-peer-deps
        
    - name: Run Tests
      run: npm run test
      env:
        CI: true
