name: Component Tests

on:
  push:
    branches:
      - testCase_feature
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        rm -rf node_modules
        npm install --legacy-peer-deps
        npm install react-scripts@4.0.3 --save-exact
        
    - name: Run Tests
      run: |
        NODE_ENV=test npx react-scripts test src/tests/component-did-catch.js --watchAll=false
      env:
        CI: true
        SKIP_PREFLIGHT_CHECK: true
