name: Component Tests

on:
  push:
    branches:
      - testCase_feature
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get all history for all branches and tags
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: |
        npm install --legacy-peer-deps
        
    - name: Run Tests
      run: |
        git config --global --add safe.directory /github/workspace
        NODE_ENV=test npx jest src/tests/component-did-catch.js --no-cache
      env:
        CI: true
        SKIP_PREFLIGHT_CHECK: true
